PublicBodyCategories.add(:ca, [
    "Administració Central",
        [ "ministerio", "Ministeris", "un Ministerio" ],
        [ "secretaria_estado", "Secretaries d'Estat", "una Secretaría de Estado"],
        [ "direccion_general", "Direccions Generals", "una Dirección General"],
        [ "agencia_estatal", "Agències Estatals i Altres Organismes", "una Agencia Estatal u órganismo dependiente"],
        [ "embajada", "Ambaixades", "una Embajada Española"],
        [ "organo_constitucional", "Òrgans Constitucionals", "un órgano constitucional"],
        [ "organo_regulador", "Organismes Reguladors", "un organismo regulador"],
        [ "empresa_publica", "Empreses Públiques", "una empresa pública"],
        [ "fundacion_publica", "Fundacions Públiques", "una fundación pública"],
        [ "universidad", "Universitats", "una universidad"],
        [ "partido_politico", "Partits Polítics", "un partido político"],
    "Administració Autonòmica",
        [ "ca", "Governs Autonòmics", "un gobierno autonómico"],
        [ "asamblea_ca", "Assemblees Autonòmiques", "una asamblea autonómica"],
        [ "delegacion_gobierno", "Delegacions del Govern", "una delegación del gobierno"],
    "Administració Local",
        [ "ayuntamiento", "Ajuntaments", "un ayuntamiento"]
])
