PublicBodyCategories.add(:eu, [
    "Administrazio Zentrala",
        [ "ministerio", "Ministerioak", "un Ministerio" ],
        [ "secretaria_estado", "Estatu Idazkaritzak", "una Secretaría de Estado"],
        [ "direccion_general", "Zuzendaritza Nagusiak", "una Dirección General"],
        [ "agencia_estatal", "Estatu Agentziak eta beste Erakundeak", "una Agencia Estatal u órganismo dependiente"],
        [ "embajada", "Enbaxadak", "una Embajada Española"],
        [ "organo_constitucional", "Organo Konstituzionalak", "un órgano constitucional"],
        [ "organo_regulador", "Erakunde Arautzaileak", "un organismo regulador"],
        [ "empresa_publica", "Enpresa Publikoak", "una empresa pública"],
        [ "fundacion_publica", "Fundazio Publikoak", "una fundación pública"],
        [ "universidad", "Unibertsitateak", "una universidad"],
        [ "partido_politico", "Alderdi Politikoak", "un partido político"],
    "Administrazio Autonomikoa",
        [ "ca", "Gobernu Autonomikoa", "un gobierno autonómico"],
        [ "asamblea_ca", "Biltzar Autonomikoak", "una asamblea autonómica"],
        [ "delegacion_gobierno", "Gobernuko Ordezkaritzak", "una delegación del gobierno"],
    "Administrazio Lokala",
        [ "ayuntamiento", "Udalak", "un ayuntamiento"]
])
