PublicBodyCategories.add(:es, [
    "Administración Central",
        [ "ministerio", "Ministerios", "un ministerio" ],
        [ "secretaria_estado", "Secretarías de Estado", "una Secretaría de Estado"],
        [ "direccion_general", "Direcciones Generales", "una Dirección General"],
        [ "agencia_estatal", "Agencias Estatales y Otros Organismos", "una agencia estatal u órganismo dependiente"],
        [ "embajada", "Embajadas", "una Embajada Española"],
        [ "organo_constitucional", "Órganos Constitucionales", "un órgano constitucional"],
        [ "organo_regulador", "Organismos Reguladores", "un organismo regulador"],
        [ "empresa_publica", "Empresas Públicas", "una empresa pública"],
        [ "fundacion_publica", "Fundaciones Públicas", "una fundación pública"],
        [ "universidad", "Universidades", "una universidad"],
        [ "partido_politico", "Partidos Políticos", "un partido político"],
    "Administración Autonómica",
        [ "ca", "Gobiernos Autónomicos", "un gobierno autonómico"],
        [ "asamblea_ca", "Asambleas Autónomicas", "una asamblea autonómica"],
        [ "delegacion_gobierno", "Delegaciones del Gobierno", "una delegación del gobierno"],
    "Administración Local",
        [ "ayuntamiento", "Ayuntamientos", "un ayuntamiento"]
])
